name: textlint-azure

on: push

jobs:
  main:
    runs-on: ubuntu-22.04  # runner OS version
    permissions:
      contents: read
    timeout-minutes: 2
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install textlint
        run: >
          npm install --save-dev
          textlint
          textlint-rule-preset-smarthr
          textlint-rule-prh
          textlint-filter-rule-allowlist
          textlint-rule-azure-product-name
      - name: Install dependent module
        run: npm install
      - name: Execute textlint
        run: npx textlint --rule azure-product-name "**/*.md"
